name: CI
on:
#  workflow_dispatch:

  push:
    branches: [ feature/ci-cd-acme ]

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0
            3.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install dependencies
        run: dotnet restore Acme\src\preproc\papersign\Vestcom.PaperSign.ACME.ProcessInput\Vestcom.PaperSign.ACME.ProcessInput.csproj

      - name: Build project
        run: msbuild.exe $Env:GITHUB_WORKSPACE\Acme\src\preproc\papersign\Vestcom.PaperSign.ACME.ProcessInput\Vestcom.PaperSign.ACME.ProcessInput.csproj

      - name: Test
        run: dotnet test --no-restore --verbosity normal Acme\src\preproc\papersign\Vestcom.PaperSign.ACME.ProcessInput\Vestcom.PaperSign.ACME.ProcessInput.csproj

        # Publish Artifact
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: AdsignsArtifact
          path: ${{ github.workspace }}

  ######## Deploy actions steps on to the targeted server #################

  Deploy:
    needs: ci
    runs-on: ubuntu-latest

    env:
      #   PROJECT_NAME: ${{ inputs.ProjectName }}
      PROJECT_NAME: adsignsproject

    steps:
      # Download artifacts
      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: AdsignsArtifact

      - name: Copy artifact to remote server
        uses: actions/ssh-auth@v0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy artifact to remote server
        uses: actions/ssh-action@master
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          command: 'scp my-artifact.zip username@remote_host:/path/to/remote/folder'

            #       - name: copy file via ssh key   ####
            #        uses: appleboy/scp-action@master
            #         with:
            #             host: ${{ secrets.HOST }}
            #             username: ${{ secrets.USERNAME }}
            #     password: ${{ secrets.PASSWORD }}
            #             port: ${{ secrets.PORT }}
            #             key: ${{ secrets.KEY }}
            #             source: "adsignsproject.zip"
            #    source: "."
            #    target: "D:/adsign-testing-now/adsignsproject.zip
            #             target: D:/GHTesting


      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ./archive.zip -d ./target
